name: jargon_onRelease

on:
  workflow_call:
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-1'
  # Setting an environment variable with the value of a configuration variable
  utility_jar: vocab-jsonld-utility-1.6.3.jar
  domain_name: ${{ github.event.client_payload.domain.name }}
  prefix: ${{ github.event.client_payload.settings.jsonld.prefix }}

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.prefix }}-pages
          token: ${{ secrets.PAT_TOKEN }}
      - run: 'echo "Domain name: ${{ env.domain_name }}"'

      - id: download-md-utility
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/utilities"
          latest: true
          fileName: "${{ env.utility_jar }}"
          tarBall: false
          zipBall: false
          extract: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - shell: bash
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          printf '%s\n' "$CLIENT_PAYLOAD" > client_payload.json
          cat client_payload.json
          rm client_payload.json
      - id: set-env
        name: output a baseurl for the release
        run: |
          baseurl=$(echo "${{ env.prefix }}" | sed -r 's/[-]+/\//g')
          version=$(echo "${{ github.event.client_payload.release.version }}" | sed -r 's/[.]+/\//g')
          domain_name="${{ env.domain_name }}"
          echo "tag_name=${{ env.prefix }}-${{ github.event.client_payload.release.version }}" >> "$GITHUB_OUTPUT"
          echo "baseurl=/vocabulary/$baseurl/$version" >> "$GITHUB_OUTPUT"
          echo "domain_name=$domain_name" >> "$GITHUB_OUTPUT"
      - name: Print the baseurl
        run: |
          echo "the baseurl is ${{ steps.set-env.outputs.baseurl }}"

      - run: 'wget -O ${{ env.prefix }}.jsonld ${{ github.event.client_payload.artefacts.jsonldVocab.url }}'
      - run: 'wget -O ${{ env.prefix }}-context.jsonld ${{ github.event.client_payload.artefacts.jsonldContext.url }}'
      - run: 'wget -O ${{ env.prefix }}-schema.jsonld ${{ github.event.client_payload.artefacts.jsonSchemas[0].url }}'
      - run: 'wget -O ${{ env.prefix }}-instance.jsonld ${{ github.event.client_payload.artefacts.jsonSchemas[1].url }}'
      - run: cat ${{ env.prefix }}.jsonld
      - run: |
          cp _data/mapping.json .
          cp _data/versions.json .
          rm -rf _data/
          rm -rf _properties/
          rm -rf _classes/
          rm -rf _code-lists/ 
      - run: java -jar ${{ env.utility_jar }} -m "md" -d "./" -i ${{ env.prefix }}.jsonld && cat out.md || cat err.md
      - run: jq '."${{ env.prefix }}" = "${{ steps.set-env.outputs.baseurl }}/"' mapping.json > _data/mapping.json
      - run: cp versions.json _data/
      - run: rm mapping.json
      - run: rm versions.json
      - run: |
          rm ${{ env.utility_jar }}
          rm batch-add.json
          rm batch-delete.json
      
      - name: update the domain branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          yq -i '.versions.${{ env.prefix }}="${{ github.event.client_payload.release.version }}"' _config_preview.yml 

          git add .
          
          git commit -m "Release ${{ github.event.client_payload.release.version }}" || echo -e "nothing to commit"
 
          git tag -a ${{ steps.set-env.outputs.tag_name }} -m "Release ${{ github.event.client_payload.release.version }}"

          git push origin ${{ steps.set-env.outputs.tag_name }}
          git push origin ${{ env.prefix }}-pages
      
          yq -i '.baseurl="${{ steps.set-env.outputs.baseurl }}"' _config_preview.yml 

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.5" # Not needed with a .ruby-version file
      - name: "Bundle install"
        run: bundle install
      - name: "Build Site"
        run: bundle exec jekyll build --config _config_preview.yml
      - name: "Deploy to AWS S3"
        run: |
          aws s3 sync ./_site/ s3://uncefact-vocab-preview-sam-bucket-private${{ steps.set-env.outputs.baseurl }} --delete --cache-control max-age=604800
          aws cloudfront create-invalidation --distribution-id "E32QP2QS6SXRHC" --paths "${{ steps.set-env.outputs.baseurl }}/*"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.set-env.outputs.tag_name }}
        run: |
          gh release create "$tag" --draft \
            --repo "$GITHUB_REPOSITORY" \
            --title "Pre-release for $tag" --notes "Published at https://test.uncefact.org${{ steps.set-env.outputs.baseurl }}/about"
          gh release upload "$tag" \
          --repo "$GITHUB_REPOSITORY" \
          ${{ env.prefix }}.jsonld
          
          [[ -s ${{ env.prefix }}-context.jsonld ]] && gh release upload "$tag" \
          --repo "$GITHUB_REPOSITORY" ${{ env.prefix }}-context.jsonld

          [[ -s ${{ env.prefix }}-schema.jsonld ]] && gh release upload "$tag" \
          --repo "$GITHUB_REPOSITORY" ${{ env.prefix }}-schema.jsonld

          [[ -s ${{ env.prefix }}-instance.jsonld ]] && gh release upload "$tag" \
          --repo "$GITHUB_REPOSITORY" ${{ env.prefix }}-instance.jsonld
  
      
  
