name: jargon_onRelease

on:
  workflow_call:
    inputs:
      vocabulary_name:
        description: 'Vocabulary name'
        type: string
        required: true
jobs:

  create_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "vocabulary_name: ${{ inputs.vocabulary_name }}"'

      - id: download-agriculture-vocabulary
        if: ${{ inputs.vocabulary_name != 'agriculture' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/vocab-agriculture"
          latest: true
          fileName: "agriculture.jsonld"
          out-file-path: "vocab"
          tarBall: false
          zipBall: false
          extract: false
      - id: download-compliance-vocabulary
        if: ${{ inputs.vocabulary_name != 'compliance' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/vocab-compliance"
          latest: true
          fileName: "compliance.jsonld"
          out-file-path: "vocab"
          tarBall: false
          zipBall: false
          extract: false
      - id: download-core-vocabulary
        if: ${{ inputs.vocabulary_name != 'core' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/vocab-core"
          latest: true
          fileName: "core.jsonld"
          out-file-path: "vocab"
          tarBall: false
          zipBall: false
          extract: false
      - id: download-tourism-vocabulary
        if: ${{ inputs.vocabulary_name != 'tourism' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/vocab-tourism"
          latest: true
          fileName: "tourism.jsonld"
          out-file-path: "vocab"
          tarBall: false
          zipBall: false
          extract: false
      - id: download-transport-vocabulary
        if: ${{ inputs.vocabulary_name != 'transport' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/vocab-transport"
          latest: true
          fileName: "transport.jsonld"
          out-file-path: "vocab"
          tarBall: false
          zipBall: false
          extract: false
      - id: download-merge-utility
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/utilities"
          latest: true
          fileName: "vocab-jsonld-merge-1.0.1.jar"
          tarBall: false
          zipBall: false
          extract: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: 'echo "field: ${{ github.event.client_payload.artefacts.jsonldVocab.url }}"'
      - run: 'echo "field: ${{ github.event.client_payload.artefacts.jsonldVocab.fileName }}"'
      - run: 'wget -O ${{ inputs.vocabulary_name }}.jsonld ${{ github.event.client_payload.artefacts.jsonldVocab.url }}'
      - run: 'mv ${{ inputs.vocabulary_name }}.jsonld vocab/'
      - run: java -jar vocab-jsonld-merge-1.0.1.jar
      - run: 'mv merged.jsonld vocab/'
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vocab/${{ inputs.vocabulary_name }}.jsonld
          git add vocab/merged.jsonld
          git commit -m "release: ${{ github.event.client_payload.release.version }}"
          git push origin main
          git tag -a ${{ github.event.client_payload.release.version }} -m "release: ${{ github.event.client_payload.release.version }}"
          git push origin ${{ github.event.client_payload.release.version }}

  package:
    needs:
      - create_tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.client_payload.release.version }}

      - name: create artifact tar
        run: |
          tar -cvzf vocabulary.tar.gz vocab/${{ inputs.vocabulary_name }}.jsonld vocab/merged.jsonld 

      - name: upload build details
        uses: actions/upload-artifact@v3
        with:
          name: vocabulary_artifact
          path: vocabulary.tar.gz

  release_tag:
    needs:
      - package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.client_payload.release.version }}

      - name: Get vocabulary
        uses: actions/download-artifact@v3
        with:
          name: vocabulary_artifact
          path: ./

      - name: extract artifact
        run: |
          tar -zxvf vocabulary.tar.gz

      - name: Create Releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.client_payload.release.version }}
          artifacts: 'vocab/${{ inputs.vocabulary_name }}.jsonld,vocab/merged.jsonld'
          token: ${{ secrets.GITHUB_TOKEN }}

  pages_preview:
    needs:
      - release_tag
    uses: uncefact/vocabulary-outputs/.github/workflows/update-jargon.yml@jargon-pages
    with:
      vocabulary_name: ${{ inputs.vocabulary_name }}
    secrets: inherit
