name: jargon_onRelease

on:
  workflow_call:
    
env:
  # Setting an environment variable with the value of a configuration variable
  utility_jar: vocab-jsonld-utility-1.6.2.jar
  domain_name: ${{ github.event.client_payload.domain.name }}

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.domain_name }}-pages
      - run: 'echo "Domain name: ${{ github.event.client_payload.domain.name }}"'

      - id: download-md-utility
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "uncefact/utilities"
          latest: true
          fileName: "${{ env.utility_jar }}"
          tarBall: false
          zipBall: false
          extract: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - shell: bash
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          printf '%s\n' "$CLIENT_PAYLOAD" > client_payload.json
          cat client_payload.json
          rm client_payload.json
      - id: sets-a-baseulr
        name: output a baseurl for the release
        run: |
          baseurl=$(echo "${{ env.domain_name }}" | sed -r 's/[-]+/\//g')
          echo "baseurl=$baseurl" >> "$GITHUB_OUTPUT"
      - name: Print the baseurl
        run: |
          echo "the baseurl is ${{ steps.sets-a-baseulr.outputs.baseurl }}"

      - run: 'wget -O ${{ github.event.client_payload.domain.name }}.jsonld ${{ github.event.client_payload.artefacts.jsonldVocab.url }}'
      #https://jargon.sh/user/unece/untp-core/s/0/artefacts/jsonldContexts/untp-core.jsonld?class=untp-core
      - run: 'wget -O ${{ github.event.client_payload.domain.name }}-context.jsonld https://jargon.sh/user/unece/${{ env.domain_name }}/v/${{ github.event.client_payload.release.version }}/artefacts/jsonldContexts/${{ env.domain_name }}.jsonld?class=${{ env.domain_name }}'
      #- run: 'wget -O ${{ github.event.client_payload.domain.name }}-context.jsonld ${{ github.event.client_payload.artefacts.jsonldContext.url }}'
      - run: cat ${{ github.event.client_payload.domain.name }}.jsonld
      - run: |
          cp _data/mapping.json .
          rm -rf _data/
          rm -rf _properties/
          rm -rf _classes/
          rm -rf _code-lists/ 
      - run: java -jar ${{ env.utility_jar }} -m "md" -d "./" -i ${{ github.event.client_payload.domain.name }}.jsonld && cat out.md || cat err.md
      - run: jq '."${{ github.event.client_payload.domain.name }}" = "/vocabulary/${{ steps.sets-a-baseulr.outputs.baseurl }}/${{ github.event.client_payload.release.version }}/"' mapping.json > _data/mapping.json
      - run: rm mapping.json
      - run: |
          rm ${{ env.utility_jar }}
          rm batch-add.json
          rm batch-delete.json
      
      - name: update the domain branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          yq -i '.baseurl="/vocabulary/${{ steps.sets-a-baseulr.outputs.baseurl }}/${{ github.event.client_payload.release.version }}"' _config_preview.yml 

          git add .
          
          git commit -m "Release ${{ github.event.client_payload.release.version }}" || echo -e "nothing to commit"
 
          git tag -a ${{ steps.sets-a-baseulr.outputs.baseurl }}/${{ github.event.client_payload.release.version }} -m "Release ${{ github.event.client_payload.release.version }}"

          git push origin ${{ steps.sets-a-baseulr.outputs.baseurl }}/${{ github.event.client_payload.release.version }}
